services:
  - type: web
    name: todo-backend
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/todo-0.0.1-SNAPSHOT.jar
    rootDir: backend
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/java
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12785566?useSSL=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: sql12785566
      - key: SPRING_DATASOURCE_PASSWORD
        value: Byv3yjSTr3
